config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get  '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name, presence: true
  validates :email, presence:true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def hello
  render html: 'Hello world'
  end

  def log_out
    session.delete(:name)
    @current_user=nil
  end

  def logged_in
    return if current_user
    redirect_to login_url
  end

  def not_logged_in
    return unless current_user
    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
before_action :not_logged_in, only: %i[new create]
  def new; end

  def create
    user = User.find_by(name: params[:session][:name])
    if user
      log_in user
      redirect_to user

    else
      flash.now[:danger] = 'This user does not exist!'
      render 'new'
    end
  end

  def destroy
   log_out
   redirect_to root_path
  end

  private

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :not_logged_in, only: %i[new create]
  before_action :logged_in, only: %i[show]
  def index
  @users=User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user=User.new
  end

  def create
    @user=User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Events App, #{@user.name}!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

  def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title='')
  base_title='your events APP'
  if page_title.empty?
    base_title
  else
    page_title + ' | ' + base_title
  end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:name] = user.name
  end

  def current_user
    if (name = session[:name])
      @current_user ||= User.find_by(name: name)
    end
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.railstutorial.org/">Events APP</a>
    by <a href="#">António Fernandes</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="#">Last Events</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "EvEnT APP", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <% if !logged_in?%>
            <li><%= link_to "Help",   '#' %></li>
            <li><%= link_to "Log in", login_path %></li>
            <% else %>
            <li><%= link_to "Hello, #{current_user.name}",   current_user %></li>
            <li><%= link_to "Events", '#' %></li>
            <li><%= link_to "Logout", logout_path, method: "delete" %></li>
            <% end %>

          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   <%= render 'layouts/shim' %>
  </head>
  <body>
   <%= render 'layouts/header'%>
    <div class="container">
    <% flash.each do |message_type, message| %>
               <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="https://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Events APP</h1>

  <h2>
    This is the home page for our
    <a href="#">Events </a>
     application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/index.html.erb
<h1>List of users</h1>
<table>
<thead>
<tr>
<th>Name</th>
<th>Email</th>
<th>Show user</th>
 <th colspan="3"></th>
</tr>
</thead>

<% @users.each do |user| %>
<tr>




<td><%= user.name %></td>
<td><%= user.email %></td>
<td><%= link_to "Show", user %> </td>
<%end%>

</tr>
</table>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
 <div class="col-md-6 col-md-offset-3">
 <div class="jumbotron">
  <%=form_for(@user, url: signup_path) do |f|  %>
    <%= render 'shared/error_messages' %>
  <%= f.label :name ,"Your Name"%>
  <%= f.text_field :name, class: 'form-control'%>

  <%=f.label :email, "Your Email"%>
  <%=f.email_field :email, class: 'form-control'  %>

  <%= f.label :password , "Your password"%>
  <%= f.password_field :password, class: 'form-control'%>

  <%= f.label :password_confirmation, "Password Confirmation"%>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
  <%= f.submit "Create My Account", class:"btn btn-primary"%>
  <%end%>
 </div>
</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>